// Registriert alle Test-Dateien (Reihenfolge = Ausgabe-Reihenfolge).
import './config.test.js';
import './store.test.js';
import './store-state.test.js';
import './metrics.test.js';
import './graph.test.js';
import './auth.test.js';
import './threadedComments.test.js';
import './fileAdapter.test.js';
import './dataQuality.test.js';
import './export.test.js';
import './tables.test.js';
import './glossary.test.js';
import './urlState.test.js';
import './snapshot.test.js';
import './contrast.test.js';
import './views-meta.test.js';
import './filterChips.test.js';
import './common.test.js';
